name: 'nyc_taxi_dbt'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_dbt' 
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_dbt:
    +materialized: table